name: build-and-test

on:
  push:
    # all branches
  pull_request:
    branches:
      - main
      - master

  # This enables the Run Workflow button on the Actions tab.
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      - uses: dylan-lang/install-opendylan@v2

      - name: Build json-test-suite
        run: ./dylan-compiler -build -jobs 2 json-test-suite

      - name: Run json-test-suite
        run: _build/bin/json-test-suite
